#!/bin/bash
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
mem_used=0
cpu_used=0
hd_used=0
#Calculate memory used and free
list_vm=`virsh list --all | awk '/running/ { print $2}'`
for i in $list_vm
do
   mem_used=`virsh dominfo $i | awk '/Used memory/ { print $3}'`
   cpu_used=`virsh dominfo $i | awk '/CPU/ {print $2}' | sed 2d`
   let "mem_used += mem_used"
   let "cpu_used += cpu_used"
done

total_mem=`free | awk '/Mem/ {print $2}'`
let "free_mem = ($total_mem - $mem_used) / 1024"

# Maybe we must devide some value for system work 
echo "$free_mem   MB memory for create new VM"
#total processor n*4 or n*3 or beter at 2 ??? 
total_cpu=`cat /proc/cpuinfo | grep "processor" | wc -l`
   let "cpu_validate = total_cpu * 2 - cpu_used"
echo "$cpu_validate free vcpu for used"


#Chek pool free
list_pool=`virsh pool-list | awk '/active/ {print $1}'`
for j in $list_pool
	do
	hd_used=`virsh pool-info $j | awk '/Allocation/ {print $2 $3}'`
	mera=`echo $hd_used |rev | cut -c1-3 | rev`	
		if [[ $mera == "TiB" ]]
			then  hd_used=`echo $hd_used*1024 | bc -l | cut -d"." -f1`
			let "hd_used += hd_used"
		else 
			hd_used=`echo $hd_used | cut -c1-3`
			let "hd_used += hd_used"
		fi
	done
#echo "$hd_used"

#Need resolve where is free at one hd
#df -h
total_hd=`df --block-size=1G /var/lib/libvirt | awk '{print $4}' | grep -v "Available"`
   let "free_hd = $total_hd - $hd_used"
echo "$free_hd  Gb free for create VM"
	oversel=`echo $free_hd | cut -c1`
if [[ $oversel == '-' ]]
	then 
	echo "DON'T USE THIS NODE!!!"
fi
